C4Component
title Biological Objects Container

Boundary(Biopatternsg,"Biopatternsg"){
    Container_Boundary(biological_objects,"Biological Objects"){
        

        Component(controller,"Rest Controller")
        Component(sbl,"Search By Levels")
        Component(od,"Object Discovery")
        Component(esa,"ExternalServicesAdapter")
        Component(tf,"Search transcription factors")
        Component(bbo,"Build biological Object")
        Component(repository,"Repository Adapter")

        Rel(controller,sbl, "Uses")
        Rel(controller,tf, "Uses")
        Rel(tf,bbo, "Uses")
        Rel(sbl,od, "Uses")
        Rel(sbl,bbo, "Uses")
        Rel(bbo,repository,"Uses")
        Rel(tf,esa,"Uses")
        Rel(od,esa,"Uses")
        Rel(bbo,esa,"Uses")
           
    }
    Container(gateway,"Gateway")
    Container(config_and_control,"ConfigAndControl")
    Container(rrg_building,"RRGBuilding")
    Container(ontologies,"Obtologies")
    ContainerDb(database, "biological_objects_db", "MongoDB", "biological objects")
    
    Rel(gateway,controller,"Json/Http")
    Rel(config_and_control,controller,"Json/Http")
    Rel(repository,ontologies,"Json/Http")
    Rel(rrg_building,controller,"Json/Http")
    Rel(repository,config_and_control,"Json/Http")
    Rel(repository,database,"read & write")
}


Boundary(external_service,"External Services"){
    System_Ext("pdb","PDB","Busqueda de complejos proteinicos")
    System_Ext("hgnc","HGNC")
    System_Ext("uniprot","UniProt")
    System_Ext("tfbind","TFbind")
    System_Ext("jasper","Jasper")

    Rel(esa,pdb,"Uses", "Json/Https")
    Rel(esa,"hgnc","Uses", "Json/Https")
    Rel(esa,uniprot,"Uses", "Json/Https")
    Rel(esa,tfbind,"Uses", "Json/Https")
    Rel(esa,jasper,"Uses", "Json/Https")
}

UpdateLayoutConfig($c4ShapeInRow="4", $c4BoundaryInRow="1")

















