C4Component
title pubmed integration container


Boundary(Biopatternsg,"Biopatternsg"){
Container_Boundary(pubmed_integration,"PubMed Integration"){

    Component(controller,"Rest Controller")
    Component(kwg,"KeywordGeneratior")
    Component(spmid,"SearchPubMedIds")
    Component(repository,"Repository Adapter")
    Component(pti,"PubTatorIntegration")
    Component(esa,"ExternalServiceAdapter")


    Rel(controller,kwg,"Uses")
    Rel(kwg,repository,"Uses") 

    Rel(controller,spmid,"Uses")
    Rel(spmid,repository,"Uses")

    Rel(controller,pti,"Uses")
    Rel(pti,repository,"Uses")
    Rel(pti,esa,"Uses")
    Rel(spmid,esa,"USes")   
             
}
Container(config_and_control,"ConfigAndControl")
Container(rrg_building,"RRGBuilding")
ContainerDb(database, "pubmed_integration_db", "MongoDB", "combinaciones, pubmedId, abstracts")

Rel(config_and_control,controller, "Json/Http")
Rel(repository,config_and_control,"Json/Http")
Rel(rrg_building,controller,"Json/Http")
Rel(repository,database,"Uses", "read & write")

}
Boundary(externalServices,"External Services"){

System_Ext("pubtator","PubTator")
System_Ext("pubmed","PubMed")

Rel(esa,pubtator,"Uses", "Json/Https")
Rel(esa,pubmed,"USes", "Json/Https")

}

UpdateLayoutConfig($c4ShapeInRow="3", $c4BoundaryInRow="1")







