C4Component
title ontologies container
Boundary(biopatternsg,"Biopatternsg"){
    Container_Boundary(ontologies,"Ontologies"){

        Component(go_adapter,"Search Gene Ontology")
        Component(controller,"Rest Controller")
        Component(mesh_adapter,"Search MESH Ontology")
        Component(repository,"Repository Adapter")
        Component(external_services, "External service Adapter")


        Rel(controller, go_adapter,"uses")
        Rel(controller, mesh_adapter,"uses")
        Rel(go_adapter, repository,"uses")
        Rel(mesh_adapter, repository,"uses")
        Rel(go_adapter, external_services,"uses")
        Rel(mesh_adapter, external_services,"uses")


    }

    Container(gateway,"Gateway")
    Container(biologicalObjects,"Biological Objects")
    ContainerDb(database, "ontologies", "MongoDB", "biological objects")

    SystemQueue(kafka, "Kafka queue")

    Rel(mesh_adapter,kafka, producer)
    
    Rel(kafka,mesh_adapter, consumer)

    Rel(gateway, controller,"uses", "Json/Http")
    
    Rel(biologicalObjects, controller,"uses", "Json/Http")
    Rel(repository,database,"read & write")
}

Boundary(externalServices,"External Services"){

System_Ext("mesh","MESH")
System_Ext("quickGo","QuickGO")

    Rel(external_services, mesh,"uses", "Json/Http")
    Rel(external_services, quickGo,"uses", "Json/Http")


}

UpdateLayoutConfig($c4ShapeInRow="4", $c4BoundaryInRow="1")

















